name: CI

on:
  push:
    branches:
    - main
  pull_request:
    branches:
    - main
jobs:
runs-on: self-hosted
 name: executing remote ssh commands using ssh key
 uses: appleboy/ssh-action@master
 with:
    host: 13.126.123.26
    username: Ubuntu
    key: ${{ secrets.KEY }}
    script: whoami
