name: CI

on:
  push:
    branches:
    - main
  pull_request:
    branches:
    - main

jobs:
  build:
    runs-on: self-hosted
    steps:
      - name: SCP Files
  # You may pin to the exact commit or the version.
  # uses: appleboy/scp-action@b476d5806f2a4c1ed5902a87fa91b0623cac7258
        uses: appleboy/scp-action@v0.0.1
        with:
             host: ${{ secrets.HOST }}
             username: ${{ secrets.USERNAME }}
             key: ${{ secrets.KEY }}
             source: "https://github.com/abhishekr28/hospitality-management-phpcode.git"
             target: "/var/www/html/hospitality-management-phpcode"
          
