

name: remote ssh command
on: [push]
jobs:

  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
    - name: Repository checkout
      uses: actions/checkout@v2
    - name: executing remote ssh commands using key
      uses: appleboy/ssh-action@master
    - name: SCP Files
      uses: appleboy/scp-action@v0.0.1
      with:
        host: ${{ secrets.SSH_HOST }}
        username: ${{ secrets.SSH_USERNAME }}
        key: ${{ secrets.SSH_PRIVATE_KEY }}
        port: ${{ secrets.SSH_PORT }}
        source: "https://github.com/abhishekr28/hospitality-management-phpcode.git"
        target: "/var/www/html/hospitality-management-phpcode"
      
