name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: copy file via ssh key
        uses: appleboy/scp-action@master
        with:
             host: ${{ secrets.HOST }}
             username: ${{ secrets.USERNAME }}
             key: ${{ secrets.KEY }}
             source: "https://github.com/abhishekr28/hospitality-management-phpcode.git"
             target: "/var/www/html"
          
      - name: Run a multi-line script
        run: 
          echo Add other actions to build,
          echo test, and deploy your project.
